apiVersion: v1
kind: Pod
metadata:
  name: access-checkpoint
spec:
  nodeName: worker1  # Specify the node name where the pod should run
  volumes:
    - name: checkpoint-volume
      hostPath:
        path: /var/lib/kubelet/checkpoints
  containers:
    - name: access-container
      image: nginx:latest
      volumeMounts:
        - mountPath: "/mnt/checkpoints"
          name: checkpoint-volume
