apiVersion: v1
kind: Pod
metadata:
  name: my-single-pod
spec:
  containers:
  - name: zookeeper
    image: digitalwonderland/zookeeper
    ports:
    - containerPort: 2181
    - containerPort: 2888
    - containerPort: 3888
  nodeSelector:
    kubernetes.io/hostname: master
